pipeline {
   agent any
   
   environment {
       DEMO='1.3'
   }

   stages {
      stage('stage-1') {
         steps {
            echo "$DEMO Stage 1"
         }
      }
      stage('stage-2') {
         input {
            message 'Proceed?'
            ok 'Do it!'
         }
         steps {
             echo "Happen when aborted?"
         }
      }
      stage('stage-3') {
         steps {
            input 'Testing 3?'
            echo 'Stage 3'
         }
      }
      stage('stage-4') {
         steps {
            echo 'Stage 4'
         }
      }
   }
}